### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by kylemadigan** [manasRK/glove-gensim#2]
Hi there I tried running the code but I get  - MemoryError. It was able to create the glove_model. txt file but it got memory error after running for a while. Is there any fix or work around? Thank you.

**Comment by manasRK** [comment]
Are you running a 32 bit Python interpreter?

**Comment by kylemadigan** [comment]
HI, yes I am using the 32 Bit python.

**Comment by manasRK** [comment]
Please use a 64bit interpreter, word2vec/Glove often run into error in a 32 bit version. You might want to change the interpreter in your IDE to run this code snippet.
