### ISSUE TITLE
index 400000 is out of bounds 

### ISSUE THREAD

**Issue by yg37** [manasRK/glove-gensim#4]
When I ran the script on glove.6B.300d.txt, I got IndexError that index 400000 is out of bounds for axis 0 with size 400000. Adding 1 to num_lines seems to fix the problem. 
`num_lines = check_num_lines_in_glove(glove_file) + 1`

**Comment by manasRK** [comment]
Hi,

Thanks for raising an issue. The other file, glove2word2vec.py handles this problem elegantly.

There's probably one less extra field, which is the token itself (50 numbers for dimensions, 1 string for token, 51 in total). So it should be enough to do + 1 in the code.
